import type { ServiceItem } from '../../types';

export const serviceDefaultsMap: Record<string, ServiceItem> = {
  'advisory-capital-solutions': {
    _id: 'advisory-capital-solutions',
    title: 'Advisory & Capital Solutions',
    category: 'OUR SERVICES',
    detailHeading: 'Strategic Advisory & Capital Structuring',
    description1: 'Strategic guidance for corporates, foundations, institutions, and sophisticated investors on portfolio strategy, asset allocation, manager selection, and investment structuring.',
    description2: 'Alpha advises corporates, foundations, institutions, and sophisticated investors on portfolio strategy, asset allocation, manager selection, and investment structuring. We also support capital raising, transaction preparation, and financial modelling. Whether the mandate is treasury optimisation, investment policy design, capital mobilisation, or transaction readiness, Alpha acts as a trusted capital partner from strategy through execution.',
    bulletsTitle: 'Comprehensive Advisory Services',
    bullets: [
      'Portfolio Strategy & Asset Allocation',
      'Investment Structuring',
      'Manager Selection',
      'Capital Raising Support',
      'Financial Modelling',
    ],
    isActive: true,
  },
  'direct-lending-fund': {
    _id: 'direct-lending-fund',
    title: 'Direct Lending Fund',
    category: 'OUR SERVICES',
    detailHeading: 'Private Debt & Senior Secured Lending',
    description1: 'Secured senior lending strategy for institutional and sophisticated investors seeking attractive risk-adjusted income.',
    description2: 'Our Direct Lending Fund targets mid-market lending opportunities offering high cash yield and senior security protections. We perform rigorous credit assessments and structuring to ensure downside protection while maximizing yields. Investors gain exposure to a diversified portfolio of private credit assets uncorrelated with traditional public equities.',
    bulletsTitle: 'Key Fund Characteristics',
    bullets: [
      'Corporate Debt Financing',
      'Acquisition Finance Solutions',
      'Secured Term Loans & Collateral',
      'Capital Preservation & Strict Covenants',
      'Consistent Monthly Cash Distribution',
    ],
    isActive: true,
  },
  'private-equity': {
    _id: 'private-equity',
    title: 'Private Equity',
    category: 'OUR SERVICES',
    detailHeading: 'Growth Capital for Mid-Market Enterprises',
    description1: 'Long-term growth capital through disciplined investment in promising businesses with active ownership approach.',
    description2: 'Alpha partners with high-potential businesses across East Africa to scale operations, upgrade management systems, and expand market footprints. We take an active, hands-on role in corporate governance, implementing strategic improvements and unlocking sustainable value for our portfolio companies and institutional investors alike.',
    bulletsTitle: 'Investment Approach',
    bullets: [
      'Mid-Market Growth Equity',
      'Strategic Expansion Support',
      'Active Board & Management Engagement',
      'Operational Value Creation Initiatives',
      'Clear Institutional Path to Exit',
    ],
    isActive: true,
  },
  'separately-managed-accounts': {
    _id: 'separately-managed-accounts',
    title: 'Separately Managed Accounts',
    category: 'OUR SERVICES',
    detailHeading: 'Tailored Discretionary Portfolio Management',
    description1: 'Bespoke discretionary portfolios in UGX or USD, tailored to your objectives, liquidity profile, risk tolerance, and reporting requirements.',
    description2: 'For individuals and institutions requiring customized asset management, Separately Managed Accounts (SMAs) offer personalized allocations across bonds, equities, and cash equivalents. Assets are held directly in your custodian name, providing complete security, custom tax optimizations, and bespoke portfolio reporting frequencies.',
    bulletsTitle: 'SMA Features & Customization',
    bullets: [
      'Customized USD & UGX Asset Allocations',
      'Direct Ownership of Underlying Securities',
      'Tax-Optimized Portfolios & Liquidity Planning',
      'Tactical Adjustments by Dedicated Managers',
      'Real-time Access & Personalized Advisory',
    ],
    isActive: true,
  },
  'unit-trusts': {
    _id: 'unit-trusts',
    title: 'Unit Trusts',
    category: 'OUR SERVICES',
    detailHeading: 'Comprehensive Investment Pools for Retail & Institutions',
    description1: 'Professionally managed unit trusts for liquidity, capital preservation, and disciplined income generation.',
    description2: 'Our Unit Trusts consolidate funds from diverse investors into premium corporate paper, government treasury bonds, and high-yielding money market assets. Under active professional management, the fund offers daily liquidity, flexible top-ups, and compounding interest structures, making it an ideal vehicle for both short-term capital parking and long-term wealth accumulation.',
    bulletsTitle: 'Comprehensive Advisory Services',
    bullets: [
      'Portfolio Strategy & Asset Allocation',
      'Investment Structuring',
      'Manager Selection',
      'Capital Raising Support',
      'Financial Modelling',
    ],
    isActive: true,
  },
  'pension-retirement': {
    _id: 'pension-retirement',
    title: 'Pension & Retirement Mandates',
    category: 'OUR SERVICES',
    detailHeading: 'Liability-Driven Portfolio Management for Schemes',
    description1: 'Retirement-focused portfolio management with liability-aware construction for trustees and scheme sponsors.',
    description2: 'Alpha works closely with board of trustees and corporate scheme sponsors to design portfolios matching the long-term pension payment schedules. We employ robust asset-liability modeling (ALM) to ensure solvency, optimize capital returns under regulatory limits, and secure stable returns for retiring beneficiaries.',
    bulletsTitle: 'Mandate Scopes',
    bullets: [
      'Asset-Liability Matching (ALM) Strategy',
      'Trustee Investment Guidance & Policy Drafting',
      'Statutory & Regulatory Compliance Reports',
      'Capital Protection during Downside Markets',
      'Diversified Real Estate & Bond Allocation',
    ],
    isActive: true,
  },
};

export const getServiceDefault = (slug: string): ServiceItem => {
  return serviceDefaultsMap[slug] ?? serviceDefaultsMap['unit-trusts'];
};
